[build]
command = "npm run prod"
functions = "lambda"
publish = "build"

[[redirects]]
from = "/_base"
to = "/.netlify/functions/_base"
status = 200

[[redirects]]
from = "/test"
to = "https://determined-curie-bc9b33.netlify.app/"
status = 200
force = true
